	function gnlinks(obj)
	{
		if(obj.value==1)
			location="http://www.hubeiwater.gov.cn/iNews/";
		if(obj.value==2)
			location="http://www.mwr.gov.cn/";
		if(obj.value==3)
			location="http://www.ycsl.gov.cn/zhengwugongkai/zuzhijigou5.htm";
		if(obj.value==4)
			location="http://www.jzhd.net/main.asp";
		if(obj.value==5)
			location="http://www.xnsl.gov.cn/ziye/zuzhijigou/z_1.htm";
		if(obj.value==6)
			location="http://www.hbhj.gov.cn/";
		if(obj.value==7)
			location="http://www.hubeihgj.gov.cn/";
		if(obj.value==8)
			location="http://sfdh.chinawater.com.cn/";
			
	}
	function zflinks(obj)
	{
		if(obj.value==1)
			location="http://www.gov.cn/";
		if(obj.value==2)
			location="http://www.hubei.gov.cn/";
		if(obj.value==3)
			location="http://www.jingzhou.gov.cn/";
		if(obj.value==4)
			location="http://www.henan.gov.cn/";
		if(obj.value==5)
			location="http://www.shanxigov.cn/";
		if(obj.value==6)
			location="http://www.sd.gov.cn/";
		if(obj.value==7)
			location="http://www.hebei.gov.cn/";
		if(obj.value==8)
			location="http://www.hebei.gov.cn/";
		if(obj.value==9)
			location="http://www.shaanxi.gov.cn/";
	}
	function zhlinks(obj)
	{
		if(obj.value==1)
			location="http://www.sina.com.cn/";
		if(obj.value==2)
			location="http://www.sohu.com/";
		if(obj.value==3)
			location="http://www.sohu.com/";
		if(obj.value==4)
			location="http://www.tom.com/";
		if(obj.value==5)
			location="http://www.qq.com/";
		if(obj.value==6)
			location="http://cn.yahoo.com/";
		if(obj.value==7)
			location="http://www.china.com/zh_cn/";
		if(obj.value==8)
			location="http://www.zaobao.com/";
		if(obj.value==9)
			location="http://www.people.com.cn/";
	}
	function yllinks(obj)
	{
		if(obj.value==1)
			location="http://ent.qq.com/";
		if(obj.value==2)
			location="http://ent.sina.com.cn/";
		if(obj.value==3)
			location="http://yule.sohu.com/";
		if(obj.value==4)
			location="http://ent.tom.com/";
		if(obj.value==5)
			location="http://ent.163.com/";
		if(obj.value==6)
			location="http://ent.phoenixtv.com/";
		if(obj.value==7)
			location="http://ent.ynet.com/";
		if(obj.value==8)
			location="http://fun.china.com/";
		if(obj.value==9)
			location="http://ent.people.com.cn/";
	}
